stages:
  prepare:
    cmd: python src/preprocess.py
    deps:
    - data/bugs.csv
    - src/preprocess.py
    params:
    - prepare.column_to_encode
    - prepare.columns_to_remove
    - prepare.label_map
    - prepare.random_state
    - prepare.target_column
    - prepare.test_size
    - prepare.text_column
    outs:
    - data/processed/test.csv
    - data/processed/train.csv
    - data/processed/val.csv
  transform:
    cmd: python src/transform.py
    deps:
    - data/processed/test.csv
    - data/processed/train.csv
    - data/processed/val.csv
    outs:
    - data/features/test.parquet
    - data/features/train.parquet
    - data/features/val.parquet
  train:
    cmd: python src/train.py --train-features data/features/train.parquet 
      --val-features data/features/val.parquet
    deps:
    - data/features/train.parquet
    - data/features/val.parquet
    - src/train.py
    outs:
    - metrics/best_model_metrics.json
    - models/best_model.pkl
